// Fun facts to show while loading questions
// Organized by subject for extra relevance, with multilingual support

import type { Language } from '../types';

const funFacts: Record<Language, Record<string, string[]>> = {
  en: {
    Science: [
      'Honey never spoils — 3,000-year-old jars still taste fine.',
      'Octopuses have three hearts and blue blood.',
      'A teaspoon of a neutron star weighs 6 billion tons.',
      'Bananas are naturally radioactive.',
      'You share 60% of your DNA with a banana.',
      'Water can boil and freeze at the same time — it\'s called the triple point.',
      'There are more bacteria in your mouth than people on Earth.',
      'Light takes 8 minutes to travel from the Sun to Earth.',
      'A single bolt of lightning contains enough energy to toast 100,000 slices of bread.',
      'Your body contains enough iron to make a 3-inch nail.',
    ],
    History: [
      'Cleopatra lived closer to the Moon landing than the pyramids.',
      'Oxford University is older than the Aztec Empire.',
      'Vikings used crystals to navigate on cloudy days.',
      'Ancient Romans used urine as mouthwash.',
      'The shortest war in history lasted 38 minutes.',
      'Napoleon was once attacked by a horde of rabbits.',
      'Ancient Egyptians used moldy bread as medicine — an early antibiotic.',
      'The Great Wall of China is not visible from space with the naked eye.',
      'Abraham Lincoln was a champion wrestler before becoming president.',
      'The oldest known joke is from 1900 BC Sumeria.',
    ],
    Gaming: [
      'Mario was originally called "Jumpman."',
      'Pac-Man was inspired by a pizza with a slice missing.',
      'The first video game was made in 1958 — Tennis for Two.',
      'Minecraft has more copies sold than any other game.',
      'The PlayStation was originally a Nintendo accessory.',
      'The Game Boy survived a bombing in the Gulf War and still works.',
      'Tetris is based on a puzzle game invented by a Soviet engineer.',
      'GTA V earned $1 billion in its first 3 days — faster than any movie.',
      'The Konami Code (↑↑↓↓←→←→BA) was created because the game was too hard for the developer.',
      'The voice of Mario has been the same actor since 1995.',
    ],
    Movies: [
      'The lion roar in MGM\'s logo is actually a tiger.',
      'Toy Story was the first fully CGI feature film.',
      'The word "mafia" is never said in The Godfather.',
      'James Bond has been played by 7 different actors.',
      'The movie Titanic cost more than the actual ship.',
      'The snow in The Wizard of Oz was made of 100% asbestos.',
      'During filming, the cast of The Lord of the Rings got matching tattoos.',
      'The famous Wilhelm scream has been used in over 400 films.',
      'Psycho was the first movie to show a toilet flushing on screen.',
      'Disney almost went bankrupt before Snow White saved the company.',
    ],
    Music: [
      '"Happy Birthday" was copyrighted until 2016.',
      'Spotify\'s most-streamed song has over 4 billion plays.',
      'Beethoven kept composing after going completely deaf.',
      'A group of flamingos is called a "flamboyance."',
      'The longest concert ever lasted over 453 hours.',
      'The average pop song has gotten 30 seconds shorter over the last 20 years.',
      'Mozart wrote his first symphony at age 8.',
      'Vinyl records are making a comeback and outsell CDs.',
      'The most expensive instrument ever sold was a Stradivarius violin for $16 million.',
      'Finland has more heavy metal bands per capita than any other country.',
    ],
    Sports: [
      'Golf is the only sport played on the Moon.',
      'Olympic gold medals are mostly made of silver.',
      'A baseball only lasts 5–7 pitches on average.',
      'Tennis was originally played with bare hands.',
      'The first Olympic Games had only one event: a footrace.',
      'A hockey puck can travel at over 100 mph.',
      'The World Cup trophy is made of 18-karat gold.',
      'Michael Jordan was cut from his high school basketball team.',
      'Table tennis balls can travel at speeds over 60 mph.',
      'Cricket matches can last up to 5 days.',
    ],
    Nature: [
      'Trees can communicate through an underground fungal network.',
      'A bolt of lightning is 5x hotter than the Sun\'s surface.',
      'Cows have best friends and get stressed when separated.',
      'There are more trees on Earth than stars in the Milky Way.',
      'Sloths can hold their breath longer than dolphins.',
      'A group of owls is called a "parliament."',
      'Dolphins sleep with one eye open.',
      'Hummingbirds are the only birds that can fly backwards.',
      'An octopus has nine brains — one central and one for each arm.',
      'Sea otters hold hands while sleeping to keep from drifting apart.',
    ],
    Food: [
      'Strawberries aren\'t actually berries — bananas are.',
      'Honey is the only food that never expires.',
      'Carrots were originally purple, not orange.',
      'Apples float because they\'re 25% air.',
      'Peanuts aren\'t nuts — they\'re legumes.',
      'White chocolate isn\'t technically chocolate — it has no cocoa solids.',
      'Ketchup was sold as medicine in the 1830s.',
      'The most expensive pizza in the world costs over $12,000.',
      'Cucumbers are 96% water.',
      'There are over 1,000 varieties of bananas in the world.',
    ],
    Travel: [
      'France is the most visited country in the world.',
      'There\'s a town in Norway called "Hell" — it freezes over.',
      'Australia is wider than the Moon.',
      'The shortest flight in the world is 57 seconds.',
      'Canada has more lakes than the rest of the world combined.',
      'Russia spans 11 time zones.',
      'Vatican City is the smallest country in the world — smaller than a golf course.',
      'The Dead Sea is so salty you float without trying.',
      'Iceland has no mosquitoes.',
      'You can walk from Alaska to Russia when the sea freezes in winter.',
    ],
    'Pop Culture': [
      'The first text message ever sent just said "Merry Christmas."',
      'More people own phones than toothbrushes.',
      'The hashtag symbol is technically called an "octothorpe."',
      'The average person spends 2 weeks of their life waiting for traffic lights.',
      'Emojis were invented in Japan in 1999.',
      'The "like" button on Facebook was almost called the "awesome" button.',
      'Netflix was originally a DVD-by-mail service.',
      'Google\'s original name was "BackRub."',
      'The first YouTube video was uploaded on April 23, 2005.',
      'The word "selfie" was added to the dictionary in 2013.',
    ],
    Art: [
      'The Mona Lisa has her own mailbox for fan letters.',
      'Vincent van Gogh only sold one painting in his lifetime.',
      'The color orange is named after the fruit, not the other way around.',
      'Picasso could draw before he could walk.',
      'The Louvre would take 100 days to see every piece for 30 seconds.',
      'The Eiffel Tower was supposed to be torn down after 20 years.',
      'Michelangelo painted the Sistine Chapel ceiling standing up, not lying down.',
      'The Great Sphinx of Giza originally had a nose — no one knows how it was lost.',
      'Blue was the last color to get a name in most languages.',
      'Salvador Dalí designed the Chupa Chups lollipop logo.',
    ],
    Tech: [
      'The first computer bug was an actual moth in the machine.',
      'Email existed before the World Wide Web.',
      'The first 1GB hard drive weighed over 500 pounds.',
      'About 90% of the world\'s data was created in the last 2 years.',
      'The first website is still online from 1991.',
      'There are more devices connected to the internet than people on Earth.',
      'The QWERTY keyboard was designed to slow typists down to prevent jamming.',
      'Wi-Fi doesn\'t stand for anything — it\'s a made-up name.',
      'The first computer mouse was made of wood.',
      'About 6,000 new computer viruses are created every month.',
    ],
  },

  ru: {
    Science: [
      'Мёд не портится — банки возрастом 3 000 лет всё ещё пригодны для еды.',
      'У осьминогов три сердца и голубая кровь.',
      'Чайная ложка нейтронной звезды весит 6 миллиардов тонн.',
      'Бананы от природы радиоактивны.',
      'У вас 60% общих генов с бананом.',
      'Вода может кипеть и замерзать одновременно — это называется тройная точка.',
      'Во рту у вас больше бактерий, чем людей на Земле.',
      'Свету нужно 8 минут, чтобы добраться от Солнца до Земли.',
      'Одна молния содержит достаточно энергии, чтобы поджарить 100 000 ломтиков хлеба.',
      'В вашем теле достаточно железа, чтобы сделать гвоздь длиной 7 см.',
    ],
    History: [
      'Клеопатра жила ближе по времени к высадке на Луну, чем к строительству пирамид.',
      'Оксфордский университет старше империи ацтеков.',
      'Викинги использовали кристаллы для навигации в пасмурную погоду.',
      'Древние римляне использовали мочу как ополаскиватель для рта.',
      'Самая короткая война в истории длилась 38 минут.',
      'На Наполеона однажды напала стая кроликов.',
      'Древние египтяне использовали заплесневелый хлеб как лекарство — ранний антибиотик.',
      'Великую Китайскую стену невозможно увидеть из космоса невооружённым глазом.',
      'Авраам Линкольн был чемпионом по борьбе до того, как стал президентом.',
      'Самая древняя известная шутка датируется 1900 годом до н.э. из Шумера.',
    ],
    Gaming: [
      'Марио изначально звали «Джампмен».',
      'Пакман был вдохновлён пиццей с недостающим куском.',
      'Первая видеоигра была создана в 1958 году — Tennis for Two.',
      'Minecraft — самая продаваемая видеоигра в истории.',
      'PlayStation изначально создавался как аксессуар для Nintendo.',
      'Game Boy пережил бомбардировку в войне в Персидском заливе и до сих пор работает.',
      'Тетрис основан на головоломке, изобретённой советским инженером.',
      'GTA V заработала $1 млрд за первые 3 дня — быстрее любого фильма.',
      'Код Konami (↑↑↓↓←→←→BA) был создан, потому что игра была слишком сложной для разработчика.',
      'Голос Марио озвучивает один и тот же актёр с 1995 года.',
    ],
    Movies: [
      'Рычание льва в заставке MGM на самом деле принадлежит тигру.',
      '«История игрушек» — первый полнометражный фильм, полностью созданный на компьютере.',
      'Слово «мафия» ни разу не произносится в «Крёстном отце».',
      'Джеймса Бонда играли 7 разных актёров.',
      'Фильм «Титаник» обошёлся дороже, чем сам корабль.',
      'Снег в «Волшебнике страны Оз» был сделан из 100% асбеста.',
      'Во время съёмок актёры «Властелина колец» сделали одинаковые татуировки.',
      'Знаменитый крик Вильгельма использовался более чем в 400 фильмах.',
      '«Психо» был первым фильмом, в котором показали смыв унитаза.',
      'Disney чуть не обанкротился, пока «Белоснежка» не спасла компанию.',
    ],
    Music: [
      'Песня «Happy Birthday» была защищена авторским правом до 2016 года.',
      'Самый прослушиваемый трек на Spotify набрал более 4 миллиардов воспроизведений.',
      'Бетховен продолжал сочинять музыку, полностью оглохнув.',
      'Группу фламинго по-английски называют «flamboyance» — великолепие.',
      'Самый длинный концерт в истории длился более 453 часов.',
      'Средняя поп-песня стала короче на 30 секунд за последние 20 лет.',
      'Моцарт написал свою первую симфонию в 8 лет.',
      'Виниловые пластинки возвращаются и продаются лучше компакт-дисков.',
      'Самый дорогой инструмент — скрипка Страдивари, проданная за $16 миллионов.',
      'В Финляндии больше хеви-метал групп на душу населения, чем в любой другой стране.',
    ],
    Sports: [
      'Гольф — единственный вид спорта, в который играли на Луне.',
      'Олимпийские золотые медали в основном сделаны из серебра.',
      'Бейсбольный мяч выдерживает в среднем всего 5–7 подач.',
      'В теннис изначально играли голыми руками.',
      'На первых Олимпийских играх был только один вид спорта: бег.',
      'Хоккейная шайба может лететь со скоростью более 160 км/ч.',
      'Кубок мира по футболу сделан из 18-каратного золота.',
      'Майкла Джордана отчислили из школьной баскетбольной команды.',
      'Мячи для настольного тенниса могут лететь со скоростью более 100 км/ч.',
      'Матч по крикету может длиться до 5 дней.',
    ],
    Nature: [
      'Деревья общаются через подземную грибную сеть.',
      'Молния в 5 раз горячее поверхности Солнца.',
      'У коров есть лучшие друзья, и они переживают, когда их разлучают.',
      'На Земле больше деревьев, чем звёзд в Млечном Пути.',
      'Ленивцы могут задерживать дыхание дольше, чем дельфины.',
      'Группу сов называют «парламентом».',
      'Дельфины спят с одним открытым глазом.',
      'Колибри — единственные птицы, которые умеют летать назад.',
      'У осьминога девять мозгов — один центральный и по одному на каждое щупальце.',
      'Морские выдры держатся за лапки во сне, чтобы не уплыть друг от друга.',
    ],
    Food: [
      'Клубника на самом деле не ягода, а вот банан — ягода.',
      'Мёд — единственный продукт, который никогда не портится.',
      'Морковь изначально была фиолетовой, а не оранжевой.',
      'Яблоки плавают, потому что на 25% состоят из воздуха.',
      'Арахис — это не орех, а бобовое растение.',
      'Белый шоколад — не настоящий шоколад: в нём нет какао-бобов.',
      'Кетчуп продавался как лекарство в 1830-х годах.',
      'Самая дорогая пицца в мире стоит более $12 000.',
      'Огурцы на 96% состоят из воды.',
      'В мире существует более 1 000 сортов бананов.',
    ],
    Travel: [
      'Франция — самая посещаемая страна в мире.',
      'В Норвегии есть город под названием «Хелл» — и там бывают заморозки.',
      'Австралия шире Луны.',
      'Самый короткий авиарейс в мире длится 57 секунд.',
      'В Канаде больше озёр, чем во всём остальном мире вместе взятом.',
      'Россия охватывает 11 часовых поясов.',
      'Ватикан — самая маленькая страна мира, меньше поля для гольфа.',
      'Мёртвое море настолько солёное, что вы плаваете без усилий.',
      'В Исландии нет комаров.',
      'Зимой, когда море замерзает, можно пешком дойти из Аляски в Россию.',
    ],
    'Pop Culture': [
      'Первое SMS-сообщение содержало всего два слова: «Merry Christmas».',
      'Телефонов в мире больше, чем зубных щёток.',
      'Символ # на самом деле называется «октоторп».',
      'В среднем человек проводит 2 недели жизни в ожидании у светофоров.',
      'Эмодзи были изобретены в Японии в 1999 году.',
      'Кнопка «лайк» в Facebook чуть не стала кнопкой «круто».',
      'Netflix изначально был сервисом DVD-по-почте.',
      'Первоначальное название Google было «BackRub».',
      'Первое видео на YouTube было загружено 23 апреля 2005 года.',
      'Слово «селфи» было добавлено в словарь в 2013 году.',
    ],
    Art: [
      'У Моны Лизы есть собственный почтовый ящик для писем от поклонников.',
      'Винсент Ван Гог продал лишь одну картину за всю жизнь.',
      'Цвет «оранжевый» назван в честь фрукта, а не наоборот.',
      'Пикассо умел рисовать раньше, чем ходить.',
      'Чтобы увидеть каждый экспонат в Лувре хотя бы на 30 секунд, понадобится 100 дней.',
      'Эйфелева башня должна была быть снесена через 20 лет.',
      'Микеланджело расписывал потолок Сикстинской капеллы стоя, а не лёжа.',
      'У Большого Сфинкса в Гизе изначально был нос — никто не знает, как он исчез.',
      'Голубой был последним цветом, получившим название в большинстве языков.',
      'Сальвадор Дали разработал логотип леденцов Chupa Chups.',
    ],
    Tech: [
      'Первый компьютерный «баг» был настоящей молью, застрявшей в машине.',
      'Электронная почта появилась раньше Всемирной паутины.',
      'Первый жёсткий диск объёмом 1 ГБ весил более 225 кг.',
      'Около 90% всех данных в мире были созданы за последние 2 года.',
      'Первый в мире веб-сайт 1991 года до сих пор работает.',
      'Устройств, подключённых к интернету, больше, чем людей на Земле.',
      'Клавиатура QWERTY была создана, чтобы замедлить печатающих и избежать заклинивания.',
      'Wi-Fi ничего не означает — это просто придуманное название.',
      'Первая компьютерная мышь была сделана из дерева.',
      'Каждый месяц создаётся около 6 000 новых компьютерных вирусов.',
    ],
  },

  de: {
    Science: [
      'Honig verdirbt nie — 3.000 Jahre alte Gläser schmecken noch einwandfrei.',
      'Kraken haben drei Herzen und blaues Blut.',
      'Ein Teelöffel eines Neutronensterns wiegt 6 Milliarden Tonnen.',
      'Bananen sind von Natur aus radioaktiv.',
      'Du teilst 60 % deiner DNA mit einer Banane.',
      'Wasser kann gleichzeitig kochen und gefrieren — das nennt man den Tripelpunkt.',
      'In deinem Mund sind mehr Bakterien als Menschen auf der Erde.',
      'Licht braucht 8 Minuten von der Sonne zur Erde.',
      'Ein einzelner Blitz enthält genug Energie, um 100.000 Scheiben Brot zu toasten.',
      'Dein Körper enthält genug Eisen, um einen 7-cm-Nagel herzustellen.',
    ],
    History: [
      'Kleopatra lebte zeitlich näher an der Mondlandung als am Bau der Pyramiden.',
      'Die Universität Oxford ist älter als das Azteken-Reich.',
      'Wikinger nutzten Kristalle, um bei bewölktem Himmel zu navigieren.',
      'Die alten Römer benutzten Urin als Mundspülung.',
      'Der kürzeste Krieg der Geschichte dauerte 38 Minuten.',
      'Napoleon wurde einmal von einer Horde Kaninchen angegriffen.',
      'Die alten Ägypter nutzten verschimmeltes Brot als Medizin — ein frühes Antibiotikum.',
      'Die Chinesische Mauer ist aus dem Weltraum mit bloßem Auge nicht sichtbar.',
      'Abraham Lincoln war ein Ringkampf-Champion, bevor er Präsident wurde.',
      'Der älteste bekannte Witz stammt aus Sumer, ca. 1900 v. Chr.',
    ],
    Gaming: [
      'Mario hieß ursprünglich „Jumpman".',
      'Pac-Man wurde von einer Pizza mit einem fehlenden Stück inspiriert.',
      'Das erste Videospiel entstand 1958 — Tennis for Two.',
      'Minecraft hat mehr verkaufte Exemplare als jedes andere Spiel.',
      'Die PlayStation war ursprünglich ein Zubehör für Nintendo.',
      'Ein Game Boy überlebte eine Bombardierung im Golfkrieg und funktioniert immer noch.',
      'Tetris basiert auf einem Puzzlespiel, das ein sowjetischer Ingenieur erfand.',
      'GTA V verdiente in den ersten 3 Tagen $1 Milliarde — schneller als jeder Film.',
      'Der Konami-Code (↑↑↓↓←→←→BA) wurde erstellt, weil das Spiel dem Entwickler zu schwer war.',
      'Die Stimme von Mario wird seit 1995 vom selben Schauspieler gesprochen.',
    ],
    Movies: [
      'Das Löwengebrüll im MGM-Logo stammt in Wirklichkeit von einem Tiger.',
      'Toy Story war der erste komplett computeranimierte Spielfilm.',
      'Das Wort „Mafia" fällt im Film Der Pate kein einziges Mal.',
      'James Bond wurde von 7 verschiedenen Schauspielern dargestellt.',
      'Der Film Titanic kostete mehr als das echte Schiff.',
      'Der Schnee im Zauberer von Oz bestand aus 100 % Asbest.',
      'Während der Dreharbeiten ließen sich die Schauspieler von Herr der Ringe passende Tattoos stechen.',
      'Der berühmte Wilhelm-Schrei wurde in über 400 Filmen verwendet.',
      'Psycho war der erste Film, der eine Toilettenspülung auf der Leinwand zeigte.',
      'Disney ging fast bankrott, bevor Schneewittchen das Unternehmen rettete.',
    ],
    Music: [
      '„Happy Birthday" war bis 2016 urheberrechtlich geschützt.',
      'Der meistgestreamte Song auf Spotify hat über 4 Milliarden Aufrufe.',
      'Beethoven komponierte weiter, nachdem er vollständig ertaubt war.',
      'Eine Gruppe Flamingos heißt auf Englisch „Flamboyance" — Extravaganz.',
      'Das längste Konzert aller Zeiten dauerte über 453 Stunden.',
      'Der durchschnittliche Popsong ist in den letzten 20 Jahren um 30 Sekunden kürzer geworden.',
      'Mozart schrieb seine erste Sinfonie im Alter von 8 Jahren.',
      'Schallplatten erleben ein Comeback und verkaufen sich besser als CDs.',
      'Das teuerste jemals verkaufte Instrument war eine Stradivari-Geige für 16 Millionen Dollar.',
      'Finnland hat mehr Heavy-Metal-Bands pro Kopf als jedes andere Land.',
    ],
    Sports: [
      'Golf ist die einzige Sportart, die auf dem Mond gespielt wurde.',
      'Olympische Goldmedaillen bestehen größtenteils aus Silber.',
      'Ein Baseball hält im Schnitt nur 5–7 Würfe.',
      'Tennis wurde ursprünglich mit bloßen Händen gespielt.',
      'Bei den ersten Olympischen Spielen gab es nur eine Disziplin: einen Wettlauf.',
      'Ein Hockeypuck kann mit über 160 km/h fliegen.',
      'Der WM-Pokal besteht aus 18-karätigem Gold.',
      'Michael Jordan wurde aus dem Basketball-Team seiner Highschool geworfen.',
      'Tischtennisbälle können mit über 100 km/h fliegen.',
      'Cricket-Spiele können bis zu 5 Tage dauern.',
    ],
    Nature: [
      'Bäume kommunizieren über ein unterirdisches Pilznetzwerk.',
      'Ein Blitz ist 5-mal heißer als die Sonnenoberfläche.',
      'Kühe haben beste Freunde und werden gestresst, wenn man sie trennt.',
      'Es gibt mehr Bäume auf der Erde als Sterne in der Milchstraße.',
      'Faultiere können länger die Luft anhalten als Delfine.',
      'Eine Gruppe von Eulen heißt „Parlament".',
      'Delfine schlafen mit einem offenen Auge.',
      'Kolibris sind die einzigen Vögel, die rückwärts fliegen können.',
      'Ein Oktopus hat neun Gehirne — eines zentral und eines pro Arm.',
      'Seeotter halten im Schlaf Händchen, um nicht auseinander zu treiben.',
    ],
    Food: [
      'Erdbeeren sind eigentlich keine Beeren — Bananen dagegen schon.',
      'Honig ist das einzige Lebensmittel, das niemals verdirbt.',
      'Karotten waren ursprünglich lila, nicht orange.',
      'Äpfel schwimmen, weil sie zu 25 % aus Luft bestehen.',
      'Erdnüsse sind keine Nüsse — sie sind Hülsenfrüchte.',
      'Weiße Schokolade ist technisch gesehen keine Schokolade — sie enthält keine Kakaomasse.',
      'Ketchup wurde in den 1830er Jahren als Medizin verkauft.',
      'Die teuerste Pizza der Welt kostet über 12.000 Dollar.',
      'Gurken bestehen zu 96 % aus Wasser.',
      'Es gibt weltweit über 1.000 Bananensorten.',
    ],
    Travel: [
      'Frankreich ist das meistbesuchte Land der Welt.',
      'In Norwegen gibt es einen Ort namens „Hell" — und er friert regelmäßig ein.',
      'Australien ist breiter als der Mond.',
      'Der kürzeste Flug der Welt dauert 57 Sekunden.',
      'Kanada hat mehr Seen als der Rest der Welt zusammen.',
      'Russland erstreckt sich über 11 Zeitzonen.',
      'Der Vatikan ist das kleinste Land der Welt — kleiner als ein Golfplatz.',
      'Das Tote Meer ist so salzig, dass man ohne Anstrengung schwimmt.',
      'Island hat keine Mücken.',
      'Man kann im Winter von Alaska nach Russland laufen, wenn das Meer zufriert.',
    ],
    'Pop Culture': [
      'Die erste SMS aller Zeiten lautete einfach „Merry Christmas".',
      'Mehr Menschen besitzen ein Handy als eine Zahnbürste.',
      'Das #-Zeichen heißt eigentlich „Octothorpe".',
      'Der Durchschnittsmensch verbringt 2 Wochen seines Lebens an roten Ampeln.',
      'Emojis wurden 1999 in Japan erfunden.',
      'Der „Gefällt mir"-Button auf Facebook hieß fast „Awesome"-Button.',
      'Netflix war ursprünglich ein DVD-per-Post-Service.',
      'Googles ursprünglicher Name war „BackRub".',
      'Das erste YouTube-Video wurde am 23. April 2005 hochgeladen.',
      'Das Wort „Selfie" wurde 2013 in den Duden aufgenommen.',
    ],
    Art: [
      'Die Mona Lisa hat ihren eigenen Briefkasten für Fanbriefe.',
      'Vincent van Gogh verkaufte zu Lebzeiten nur ein einziges Gemälde.',
      'Die Farbe Orange ist nach der Frucht benannt, nicht umgekehrt.',
      'Picasso konnte zeichnen, bevor er laufen konnte.',
      'Man bräuchte 100 Tage, um jedes Werk im Louvre 30 Sekunden lang zu betrachten.',
      'Der Eiffelturm sollte nach 20 Jahren abgerissen werden.',
      'Michelangelo malte die Decke der Sixtinischen Kapelle stehend, nicht liegend.',
      'Die Große Sphinx von Gizeh hatte ursprünglich eine Nase — niemand weiß, wie sie verloren ging.',
      'Blau war die letzte Farbe, die in den meisten Sprachen einen Namen bekam.',
      'Salvador Dalí entwarf das Logo der Chupa-Chups-Lutscher.',
    ],
    Tech: [
      'Der erste Computer-Bug war eine echte Motte in der Maschine.',
      'E-Mail gab es schon vor dem World Wide Web.',
      'Die erste 1-GB-Festplatte wog über 225 Kilogramm.',
      'Rund 90 % aller Daten weltweit wurden in den letzten 2 Jahren erzeugt.',
      'Die erste Webseite von 1991 ist immer noch online.',
      'Es gibt mehr internetfähige Geräte als Menschen auf der Erde.',
      'Die QWERTY-Tastatur wurde entworfen, um Tipper zu verlangsamen und Verklemmungen zu verhindern.',
      'Wi-Fi steht für gar nichts — es ist ein erfundener Name.',
      'Die erste Computermaus war aus Holz.',
      'Jeden Monat werden rund 6.000 neue Computerviren erstellt.',
    ],
  },

  pl: {
    Science: [
      'Miód nigdy się nie psuje — 3000-letnie słoiki wciąż nadają się do jedzenia.',
      'Ośmiornice mają trzy serca i niebieską krew.',
      'Łyżeczka gwiazdy neutronowej waży 6 miliardów ton.',
      'Banany są naturalnie radioaktywne.',
      'Dzielisz 60% swojego DNA z bananem.',
      'Woda może wrzeć i zamarzać jednocześnie — to tak zwany punkt potrójny.',
      'W twoich ustach jest więcej bakterii niż ludzi na Ziemi.',
      'Światło potrzebuje 8 minut, by dotrzeć ze Słońca na Ziemię.',
      'Jeden piorun zawiera wystarczająco dużo energii, by opiec 100 000 kromek chleba.',
      'Twoje ciało zawiera wystarczająco dużo żelaza, by zrobić 7-centymetrowy gwóźdź.',
    ],
    History: [
      'Kleopatra żyła bliżej czasów lądowania na Księżycu niż budowy piramid.',
      'Uniwersytet Oksfordzki jest starszy od imperium Azteków.',
      'Wikingowie używali kryształów do nawigacji w pochmurne dni.',
      'Starożytni Rzymianie używali moczu jako płynu do płukania ust.',
      'Najkrótsza wojna w historii trwała 38 minut.',
      'Napoleon został kiedyś zaatakowany przez stado królików.',
      'Starożytni Egipcjanie używali spleśniałego chleba jako lekarstwa — wczesny antybiotyk.',
      'Wielki Mur Chiński nie jest widoczny z kosmosu gołym okiem.',
      'Abraham Lincoln był mistrzem zapasów, zanim został prezydentem.',
      'Najstarszy znany żart pochodzi z Sumeru, z 1900 r. p.n.e.',
    ],
    Gaming: [
      'Mario początkowo nazywał się „Jumpman".',
      'Pac-Man został zainspirowany pizzą z brakującym kawałkiem.',
      'Pierwsza gra wideo powstała w 1958 roku — Tennis for Two.',
      'Minecraft ma więcej sprzedanych kopii niż jakakolwiek inna gra.',
      'PlayStation był pierwotnie akcesorium do Nintendo.',
      'Game Boy przetrwał bombardowanie w czasie wojny w Zatoce Perskiej i nadal działa.',
      'Tetris opiera się na łamigłówce wymyślonej przez radzieckiego inżyniera.',
      'GTA V zarobiło miliard dolarów w 3 dni — szybciej niż jakikolwiek film.',
      'Kod Konami (↑↑↓↓←→←→BA) powstał, bo gra była za trudna dla dewelopera.',
      'Głos Mario jest nagrywany przez tego samego aktora od 1995 roku.',
    ],
    Movies: [
      'Ryk lwa w logo MGM to w rzeczywistości ryk tygrysa.',
      'Toy Story był pierwszym pełnometrażowym filmem stworzonym w całości komputerowo.',
      'Słowo „mafia" nie pada ani razu w filmie Ojciec Chrzestny.',
      'James Bond był grany przez 7 różnych aktorów.',
      'Film Titanic kosztował więcej niż sam statek.',
      'Śnieg w Czarnoksiężniku z Krainy Oz był zrobiony ze 100% azbestu.',
      'Podczas kręcenia Władcy Pierścieni aktorzy zrobili sobie pasujące tatuaże.',
      'Słynny krzyk Wilhelma został użyty w ponad 400 filmach.',
      'Psychoza był pierwszym filmem, który pokazał spłukiwanie toalety na ekranie.',
      'Disney prawie zbankrutował, zanim Królewna Śnieżka uratowała firmę.',
    ],
    Music: [
      '„Happy Birthday" było objęte prawem autorskim aż do 2016 roku.',
      'Najczęściej odtwarzany utwór na Spotify ma ponad 4 miliardy odsłuchań.',
      'Beethoven nadal komponował po całkowitej utracie słuchu.',
      'Grupa flamingów po angielsku nazywa się „flamboyance" — ostentacja.',
      'Najdłuższy koncert w historii trwał ponad 453 godziny.',
      'Przeciętny utwór pop skrócił się o 30 sekund w ciągu ostatnich 20 lat.',
      'Mozart napisał swoją pierwszą symfonię w wieku 8 lat.',
      'Płyty winylowe wracają do łask i sprzedają się lepiej niż płyty CD.',
      'Najdroższy instrument, jaki kiedykolwiek sprzedano, to skrzypce Stradivariusa za 16 milionów dolarów.',
      'Finlandia ma więcej zespołów heavy metalowych na mieszkańca niż jakikolwiek inny kraj.',
    ],
    Sports: [
      'Golf to jedyny sport, w który grano na Księżycu.',
      'Olimpijskie złote medale są w większości zrobione ze srebra.',
      'Piłka bejsbolowa wytrzymuje średnio tylko 5–7 rzutów.',
      'W tenisa pierwotnie grano gołymi rękami.',
      'Pierwsze igrzyska olimpijskie miały tylko jedną konkurencję: bieg.',
      'Krążek hokejowy może lecieć z prędkością ponad 160 km/h.',
      'Puchar Świata FIFA jest zrobiony z 18-karatowego złota.',
      'Michael Jordan został odrzucony z drużyny koszykówki w liceum.',
      'Piłeczki do tenisa stołowego mogą lecieć z prędkością ponad 100 km/h.',
      'Mecze krykieta mogą trwać do 5 dni.',
    ],
    Nature: [
      'Drzewa komunikują się przez podziemną sieć grzybni.',
      'Błyskawica jest 5 razy gorętsza niż powierzchnia Słońca.',
      'Krowy mają najlepsze przyjaciółki i stresują się, gdy je rozdzielisz.',
      'Na Ziemi jest więcej drzew niż gwiazd w Drodze Mlecznej.',
      'Leniwce potrafią wstrzymać oddech dłużej niż delfiny.',
      'Grupę sów nazywa się „parlamentem".',
      'Delfiny śpią z jednym otwartym okiem.',
      'Kolibry to jedyne ptaki, które mogą latać do tyłu.',
      'Ośmiornica ma dziewięć mózgów — jeden centralny i po jednym na każde ramię.',
      'Wydry morskie trzymają się za łapki podczas snu, żeby nie odpłynąć od siebie.',
    ],
    Food: [
      'Truskawki to właściwie nie jagody — za to banany jak najbardziej.',
      'Miód to jedyne jedzenie, które nigdy się nie przeterminuje.',
      'Marchewki były pierwotnie fioletowe, a nie pomarańczowe.',
      'Jabłka unoszą się na wodzie, bo składają się w 25% z powietrza.',
      'Orzeszki ziemne to nie orzechy — to rośliny strączkowe.',
      'Biała czekolada to technicznie nie czekolada — nie zawiera masy kakaowej.',
      'Ketchup był sprzedawany jako lekarstwo w latach 30. XIX wieku.',
      'Najdroższa pizza na świecie kosztuje ponad 12 000 dolarów.',
      'Ogórki składają się w 96% z wody.',
      'Na świecie istnieje ponad 1000 odmian bananów.',
    ],
    Travel: [
      'Francja jest najczęściej odwiedzanym krajem na świecie.',
      'W Norwegii jest miasteczko o nazwie „Hell" — i regularnie tam zamarza.',
      'Australia jest szersza niż Księżyc.',
      'Najkrótszy lot na świecie trwa 57 sekund.',
      'Kanada ma więcej jezior niż cała reszta świata razem wzięta.',
      'Rosja rozciąga się na 11 stref czasowych.',
      'Watykan to najmniejszy kraj na świecie — mniejszy od pola golfowego.',
      'Morze Martwe jest tak słone, że unosisz się bez wysiłku.',
      'Na Islandii nie ma komarów.',
      'Zimą, gdy morze zamarza, można przejść pieszo z Alaski do Rosji.',
    ],
    'Pop Culture': [
      'Pierwsza wiadomość SMS brzmiała po prostu „Merry Christmas".',
      'Więcej ludzi ma telefony niż szczoteczki do zębów.',
      'Symbol # oficjalnie nazywa się „octothorpe".',
      'Przeciętny człowiek spędza 2 tygodnie życia czekając na zielone światło.',
      'Emoji zostały wynalezione w Japonii w 1999 roku.',
      'Przycisk „lubię to" na Facebooku prawie został nazwany przyciskiem „super".',
      'Netflix zaczynał jako serwis wypożyczania DVD pocztą.',
      'Pierwotna nazwa Google to „BackRub".',
      'Pierwszy film na YouTube został przesłany 23 kwietnia 2005 roku.',
      'Słowo „selfie" zostało dodane do słownika w 2013 roku.',
    ],
    Art: [
      'Mona Lisa ma własną skrzynkę pocztową na listy od fanów.',
      'Vincent van Gogh sprzedał za życia tylko jeden obraz.',
      'Kolor pomarańczowy został nazwany od owocu, a nie odwrotnie.',
      'Picasso potrafił rysować, zanim nauczył się chodzić.',
      'Obejrzenie każdego dzieła w Luwrze przez 30 sekund zajęłoby 100 dni.',
      'Wieża Eiffla miała być rozebrana po 20 latach.',
      'Michał Anioł malował sufit Kaplicy Sykstyńskiej stojąc, a nie leżąc.',
      'Wielki Sfinks w Gizie miał pierwotnie nos — nikt nie wie, jak go stracił.',
      'Niebieski był ostatnim kolorem, który otrzymał nazwę w większości języków.',
      'Salvador Dalí zaprojektował logo lizaków Chupa Chups.',
    ],
    Tech: [
      'Pierwszy komputerowy „bug" był prawdziwą ćmą, która utknęła w maszynie.',
      'E-mail istniał przed powstaniem World Wide Web.',
      'Pierwszy dysk twardy o pojemności 1 GB ważył ponad 225 kilogramów.',
      'Około 90% światowych danych powstało w ciągu ostatnich 2 lat.',
      'Pierwsza strona internetowa z 1991 roku wciąż działa.',
      'Na świecie jest więcej urządzeń podłączonych do internetu niż ludzi na Ziemi.',
      'Klawiatura QWERTY została zaprojektowana, by spowolnić piszących i zapobiec zakleszczeniom.',
      'Wi-Fi nic nie oznacza — to wymyślona nazwa.',
      'Pierwsza mysz komputerowa była zrobiona z drewna.',
      'Co miesiąc tworzy się około 6000 nowych wirusów komputerowych.',
    ],
  },

  es: {
    Science: [
      'La miel nunca se echa a perder — frascos de 3.000 años siguen en buen estado.',
      'Los pulpos tienen tres corazones y sangre azul.',
      'Una cucharadita de una estrella de neutrones pesa 6 mil millones de toneladas.',
      'Los plátanos son naturalmente radiactivos.',
      'Compartes el 60% de tu ADN con un plátano.',
      'El agua puede hervir y congelarse al mismo tiempo — se llama punto triple.',
      'Hay más bacterias en tu boca que personas en la Tierra.',
      'La luz tarda 8 minutos en viajar del Sol a la Tierra.',
      'Un solo rayo contiene suficiente energía para tostar 100.000 rebanadas de pan.',
      'Tu cuerpo contiene suficiente hierro para hacer un clavo de 7 centímetros.',
    ],
    History: [
      'Cleopatra vivió más cerca del alunizaje que de la construcción de las pirámides.',
      'La Universidad de Oxford es más antigua que el Imperio Azteca.',
      'Los vikingos usaban cristales para navegar en días nublados.',
      'Los antiguos romanos usaban orina como enjuague bucal.',
      'La guerra más corta de la historia duró 38 minutos.',
      'Napoleón fue atacado una vez por una horda de conejos.',
      'Los antiguos egipcios usaban pan mohoso como medicina — un antibiótico temprano.',
      'La Gran Muralla China no es visible desde el espacio a simple vista.',
      'Abraham Lincoln fue campeón de lucha libre antes de ser presidente.',
      'El chiste más antiguo conocido es de Sumeria, del 1900 a.C.',
    ],
    Gaming: [
      'Mario se llamaba originalmente "Jumpman."',
      'Pac-Man se inspiró en una pizza a la que le faltaba un trozo.',
      'El primer videojuego se creó en 1958 — Tennis for Two.',
      'Minecraft ha vendido más copias que cualquier otro juego.',
      'La PlayStation fue originalmente un accesorio de Nintendo.',
      'Un Game Boy sobrevivió a un bombardeo en la Guerra del Golfo y aún funciona.',
      'Tetris se basa en un rompecabezas inventado por un ingeniero soviético.',
      'GTA V ganó mil millones de dólares en sus primeros 3 días — más rápido que cualquier película.',
      'El Código Konami (↑↑↓↓←→←→BA) fue creado porque el juego era demasiado difícil para el desarrollador.',
      'La voz de Mario ha sido del mismo actor desde 1995.',
    ],
    Movies: [
      'El rugido de león del logo de MGM es en realidad de un tigre.',
      'Toy Story fue el primer largometraje hecho completamente por computadora.',
      'La palabra "mafia" nunca se dice en El Padrino.',
      'James Bond ha sido interpretado por 7 actores diferentes.',
      'La película Titanic costó más que el barco real.',
      'La nieve en El Mago de Oz estaba hecha de 100% asbesto.',
      'Durante el rodaje, el reparto de El Señor de los Anillos se hizo tatuajes a juego.',
      'El famoso grito de Wilhelm se ha usado en más de 400 películas.',
      'Psicosis fue la primera película en mostrar un inodoro siendo tirado en pantalla.',
      'Disney casi quiebra antes de que Blancanieves salvara la compañía.',
    ],
    Music: [
      '"Cumpleaños Feliz" estuvo protegido por derechos de autor hasta 2016.',
      'La canción más reproducida en Spotify tiene más de 4 mil millones de reproducciones.',
      'Beethoven siguió componiendo después de quedarse completamente sordo.',
      'A un grupo de flamencos en inglés se le llama "flamboyance" — extravagancia.',
      'El concierto más largo de la historia duró más de 453 horas.',
      'La canción pop promedio se ha acortado 30 segundos en los últimos 20 años.',
      'Mozart escribió su primera sinfonía a los 8 años.',
      'Los discos de vinilo están de vuelta y se venden más que los CDs.',
      'El instrumento más caro jamás vendido fue un violín Stradivarius por 16 millones de dólares.',
      'Finlandia tiene más bandas de heavy metal per cápita que cualquier otro país.',
    ],
    Sports: [
      'El golf es el único deporte que se ha jugado en la Luna.',
      'Las medallas de oro olímpicas están hechas principalmente de plata.',
      'Una pelota de béisbol dura en promedio solo 5 a 7 lanzamientos.',
      'El tenis se jugaba originalmente con las manos desnudas.',
      'Los primeros Juegos Olímpicos solo tenían una prueba: una carrera a pie.',
      'Un disco de hockey puede viajar a más de 160 km/h.',
      'El trofeo de la Copa del Mundo está hecho de oro de 18 quilates.',
      'Michael Jordan fue cortado del equipo de baloncesto de su escuela secundaria.',
      'Las pelotas de tenis de mesa pueden viajar a más de 100 km/h.',
      'Los partidos de cricket pueden durar hasta 5 días.',
    ],
    Nature: [
      'Los árboles se comunican a través de una red subterránea de hongos.',
      'Un rayo es 5 veces más caliente que la superficie del Sol.',
      'Las vacas tienen mejores amigas y se estresan cuando las separan.',
      'Hay más árboles en la Tierra que estrellas en la Vía Láctea.',
      'Los perezosos pueden aguantar la respiración más tiempo que los delfines.',
      'A un grupo de búhos se le llama "parlamento."',
      'Los delfines duermen con un ojo abierto.',
      'Los colibríes son los únicos pájaros que pueden volar hacia atrás.',
      'Un pulpo tiene nueve cerebros — uno central y uno por cada brazo.',
      'Las nutrias marinas se toman de las manos al dormir para no separarse.',
    ],
    Food: [
      'Las fresas en realidad no son bayas — los plátanos sí lo son.',
      'La miel es el único alimento que nunca caduca.',
      'Las zanahorias eran originalmente moradas, no naranjas.',
      'Las manzanas flotan porque son 25% aire.',
      'Los cacahuetes no son frutos secos — son legumbres.',
      'El chocolate blanco no es técnicamente chocolate — no tiene sólidos de cacao.',
      'El kétchup se vendía como medicina en la década de 1830.',
      'La pizza más cara del mundo cuesta más de 12.000 dólares.',
      'Los pepinos son 96% agua.',
      'Hay más de 1.000 variedades de plátanos en el mundo.',
    ],
    Travel: [
      'Francia es el país más visitado del mundo.',
      'Hay un pueblo en Noruega llamado "Hell" — y se congela en invierno.',
      'Australia es más ancha que la Luna.',
      'El vuelo más corto del mundo dura 57 segundos.',
      'Canadá tiene más lagos que el resto del mundo junto.',
      'Rusia abarca 11 zonas horarias.',
      'La Ciudad del Vaticano es el país más pequeño del mundo — más pequeño que un campo de golf.',
      'El Mar Muerto es tan salado que flotas sin esfuerzo.',
      'Islandia no tiene mosquitos.',
      'Puedes caminar de Alaska a Rusia cuando el mar se congela en invierno.',
    ],
    'Pop Culture': [
      'El primer mensaje de texto enviado decía simplemente "Merry Christmas."',
      'Más personas tienen teléfonos que cepillos de dientes.',
      'El símbolo # técnicamente se llama "octothorpe."',
      'La persona promedio pasa 2 semanas de su vida esperando en semáforos.',
      'Los emojis se inventaron en Japón en 1999.',
      'El botón de "me gusta" de Facebook casi se llamó el botón de "genial."',
      'Netflix fue originalmente un servicio de DVD por correo.',
      'El nombre original de Google era "BackRub."',
      'El primer video de YouTube se subió el 23 de abril de 2005.',
      'La palabra "selfie" se añadió al diccionario en 2013.',
    ],
    Art: [
      'La Mona Lisa tiene su propio buzón para cartas de admiradores.',
      'Vincent van Gogh solo vendió un cuadro en toda su vida.',
      'El color naranja lleva el nombre de la fruta, no al revés.',
      'Picasso sabía dibujar antes de aprender a caminar.',
      'Se necesitarían 100 días para ver cada obra del Louvre durante 30 segundos.',
      'La Torre Eiffel iba a ser demolida después de 20 años.',
      'Miguel Ángel pintó el techo de la Capilla Sixtina de pie, no acostado.',
      'La Gran Esfinge de Guiza originalmente tenía nariz — nadie sabe cómo se perdió.',
      'El azul fue el último color en recibir nombre en la mayoría de los idiomas.',
      'Salvador Dalí diseñó el logotipo de los caramelos Chupa Chups.',
    ],
    Tech: [
      'El primer "bug" informático fue una polilla real atrapada en la máquina.',
      'El correo electrónico existió antes de la World Wide Web.',
      'El primer disco duro de 1 GB pesaba más de 225 kilogramos.',
      'Aproximadamente el 90% de los datos del mundo se crearon en los últimos 2 años.',
      'El primer sitio web de 1991 sigue en línea.',
      'Hay más dispositivos conectados a internet que personas en la Tierra.',
      'El teclado QWERTY fue diseñado para ralentizar a los mecanógrafos y evitar atascos.',
      'Wi-Fi no significa nada — es un nombre inventado.',
      'El primer ratón de computadora estaba hecho de madera.',
      'Se crean aproximadamente 6.000 nuevos virus informáticos cada mes.',
    ],
  },
};

// General facts as fallback
const generalFacts: Record<Language, string[]> = {
  en: [
    'A day on Venus is longer than its year.',
    'Sharks are older than trees.',
    'The inventor of the Pringles can is buried in one.',
    'Scotland\'s national animal is the unicorn.',
    'A jiffy is an actual unit of time: 1/100th of a second.',
    'The human nose can detect over 1 trillion scents.',
    'Wombat poop is cube-shaped.',
    'There are more possible chess games than atoms in the universe.',
    'Your brain uses 20% of your body\'s total energy.',
    'Honey bees can recognize human faces.',
    'A cloud can weigh over a million pounds.',
    'Humans glow in the dark, but it\'s too faint for our eyes to see.',
    'The shortest war in history was between Britain and Zanzibar — it lasted 38 to 45 minutes.',
    'Astronauts grow up to 2 inches taller in space.',
    'The average person walks about 100,000 miles in a lifetime.',
  ],
  ru: [
    'День на Венере длиннее, чем её год.',
    'Акулы древнее деревьев.',
    'Изобретатель банки Pringles похоронен в одной из них.',
    'Национальное животное Шотландии — единорог.',
    'Джиффи — настоящая единица времени: одна сотая секунды.',
    'Человеческий нос способен различать более триллиона запахов.',
    'Фекалии вомбата имеют форму куба.',
    'Возможных шахматных партий больше, чем атомов во Вселенной.',
    'Ваш мозг использует 20% всей энергии тела.',
    'Медоносные пчёлы могут узнавать человеческие лица.',
    'Облако может весить более 450 тонн.',
    'Люди светятся в темноте, но слишком слабо, чтобы наши глаза это видели.',
    'Самая короткая война была между Британией и Занзибаром — она длилась от 38 до 45 минут.',
    'Астронавты вырастают в космосе до 5 сантиметров.',
    'За жизнь средний человек проходит около 160 000 километров.',
  ],
  de: [
    'Ein Tag auf der Venus ist länger als ein ganzes Venus-Jahr.',
    'Haie sind älter als Bäume.',
    'Der Erfinder der Pringles-Dose wurde in einer beerdigt.',
    'Schottlands Nationaltier ist das Einhorn.',
    'Ein Jiffy ist eine echte Zeiteinheit: eine Hundertstelsekunde.',
    'Die menschliche Nase kann über eine Billion Gerüche unterscheiden.',
    'Wombat-Kot ist würfelförmig.',
    'Es gibt mehr mögliche Schachpartien als Atome im Universum.',
    'Dein Gehirn verbraucht 20 % der gesamten Körperenergie.',
    'Honigbienen können menschliche Gesichter erkennen.',
    'Eine Wolke kann über 450 Tonnen wiegen.',
    'Menschen leuchten im Dunkeln, aber zu schwach für unsere Augen.',
    'Der kürzeste Krieg war zwischen Großbritannien und Sansibar — er dauerte 38 bis 45 Minuten.',
    'Astronauten wachsen im Weltraum bis zu 5 Zentimeter.',
    'Ein Durchschnittsmensch läuft in seinem Leben etwa 160.000 Kilometer.',
  ],
  pl: [
    'Dzień na Wenus jest dłuższy niż jej rok.',
    'Rekiny są starsze niż drzewa.',
    'Wynalazca puszki Pringles został w niej pochowany.',
    'Narodowym zwierzęciem Szkocji jest jednorożec.',
    'Jiffy to prawdziwa jednostka czasu: jedna setna sekundy.',
    'Ludzki nos potrafi rozróżnić ponad bilion zapachów.',
    'Odchody wombata mają kształt sześcianu.',
    'Możliwych partii szachowych jest więcej niż atomów we wszechświecie.',
    'Twój mózg zużywa 20% całej energii ciała.',
    'Pszczoły miodne potrafią rozpoznawać ludzkie twarze.',
    'Chmura może ważyć ponad 450 ton.',
    'Ludzie świecą w ciemności, ale zbyt słabo, by nasze oczy to widziały.',
    'Najkrótsza wojna była między Wielką Brytanią a Zanzibarem — trwała od 38 do 45 minut.',
    'Astronauci rosną w kosmosie nawet o 5 centymetrów.',
    'Przeciętny człowiek przechodzi w życiu około 160 000 kilometrów.',
  ],
  es: [
    'Un día en Venus dura más que su propio año.',
    'Los tiburones son más antiguos que los árboles.',
    'El inventor del bote de Pringles fue enterrado en uno.',
    'El animal nacional de Escocia es el unicornio.',
    'Un jiffy es una unidad de tiempo real: una centésima de segundo.',
    'La nariz humana puede detectar más de un billón de olores.',
    'Las heces de los wombats tienen forma de cubo.',
    'Hay más partidas de ajedrez posibles que átomos en el universo.',
    'Tu cerebro usa el 20% de la energía total de tu cuerpo.',
    'Las abejas pueden reconocer rostros humanos.',
    'Una nube puede pesar más de 450 toneladas.',
    'Los humanos brillamos en la oscuridad, pero es demasiado tenue para nuestros ojos.',
    'La guerra más corta fue entre Gran Bretaña y Zanzíbar — duró entre 38 y 45 minutos.',
    'Los astronautas crecen hasta 5 centímetros en el espacio.',
    'La persona promedio camina unos 160.000 kilómetros en su vida.',
  ],
};

// Track shown facts to avoid repeats within a session
const shownFacts = new Set<string>();

export function getRandomFunFact(subject?: string | null, language: Language = 'en'): string {
  const langFacts = funFacts[language] || funFacts.en;
  const langGeneral = generalFacts[language] || generalFacts.en;

  const pool = subject && langFacts[subject]
    ? [...langFacts[subject], ...langGeneral]
    : langGeneral;

  // Filter out already-shown facts
  const available = pool.filter(f => !shownFacts.has(f));

  // If all facts have been shown, reset and start fresh
  const pickFrom = available.length > 0 ? available : pool;
  if (available.length === 0) {
    shownFacts.clear();
  }

  const index = Math.floor(Math.random() * pickFrom.length);
  const fact = pickFrom[index];
  shownFacts.add(fact);
  return fact;
}

// Reset shown facts (call when starting a new game)
export function resetShownFacts() {
  shownFacts.clear();
}
