// Fun facts to show while loading questions
// Organized by subject for extra relevance, with multilingual support

import type { Language } from '../types';

const funFacts: Record<Language, Record<string, string[]>> = {
  en: {
    Science: [
      'Honey never spoils — 3,000-year-old jars still taste fine.',
      'Octopuses have three hearts and blue blood.',
      'A teaspoon of a neutron star weighs 6 billion tons.',
      'Bananas are naturally radioactive.',
      'You share 60% of your DNA with a banana.',
    ],
    History: [
      'Cleopatra lived closer to the Moon landing than the pyramids.',
      'Oxford University is older than the Aztec Empire.',
      'Vikings used crystals to navigate on cloudy days.',
      'Ancient Romans used urine as mouthwash.',
      'The shortest war in history lasted 38 minutes.',
    ],
    Gaming: [
      'Mario was originally called "Jumpman."',
      'Pac-Man was inspired by a pizza with a slice missing.',
      'The first video game was made in 1958 — Tennis for Two.',
      'Minecraft has more copies sold than any other game.',
      'The PlayStation was originally a Nintendo accessory.',
    ],
    Movies: [
      'The lion roar in MGM\'s logo is actually a tiger.',
      'Toy Story was the first fully CGI feature film.',
      'The word "mafia" is never said in The Godfather.',
      'James Bond has been played by 7 different actors.',
      'The movie Titanic cost more than the actual ship.',
    ],
    Music: [
      '"Happy Birthday" was copyrighted until 2016.',
      'Spotify\'s most-streamed song has over 4 billion plays.',
      'Beethoven kept composing after going completely deaf.',
      'A group of flamingos is called a "flamboyance."',
      'The longest concert ever lasted over 453 hours.',
    ],
    Sports: [
      'Golf is the only sport played on the Moon.',
      'Olympic gold medals are mostly made of silver.',
      'A baseball only lasts 5–7 pitches on average.',
      'Tennis was originally played with bare hands.',
      'The first Olympic Games had only one event: a footrace.',
    ],
    Nature: [
      'Trees can communicate through an underground fungal network.',
      'A bolt of lightning is 5x hotter than the Sun\'s surface.',
      'Cows have best friends and get stressed when separated.',
      'There are more trees on Earth than stars in the Milky Way.',
      'Sloths can hold their breath longer than dolphins.',
    ],
    Food: [
      'Strawberries aren\'t actually berries — bananas are.',
      'Honey is the only food that never expires.',
      'Carrots were originally purple, not orange.',
      'Apples float because they\'re 25% air.',
      'Peanuts aren\'t nuts — they\'re legumes.',
    ],
    Travel: [
      'France is the most visited country in the world.',
      'There\'s a town in Norway called "Hell" — it freezes over.',
      'Australia is wider than the Moon.',
      'The shortest flight in the world is 57 seconds.',
      'Canada has more lakes than the rest of the world combined.',
    ],
    'Pop Culture': [
      'The first text message ever sent just said "Merry Christmas."',
      'More people own phones than toothbrushes.',
      'The hashtag symbol is technically called an "octothorpe."',
      'The average person spends 2 weeks of their life waiting for traffic lights.',
      'Emojis were invented in Japan in 1999.',
    ],
    Art: [
      'The Mona Lisa has her own mailbox for fan letters.',
      'Vincent van Gogh only sold one painting in his lifetime.',
      'The color orange is named after the fruit, not the other way around.',
      'Picasso could draw before he could walk.',
      'The Louvre would take 100 days to see every piece for 30 seconds.',
    ],
    Tech: [
      'The first computer bug was an actual moth in the machine.',
      'Email existed before the World Wide Web.',
      'The first 1GB hard drive weighed over 500 pounds.',
      'About 90% of the world\'s data was created in the last 2 years.',
      'The first website is still online from 1991.',
    ],
  },

  he: {
    Science: [
      'דבש לא מתקלקל לעולם — צנצנות בנות 3,000 שנה עדיין טעימות.',
      'לתמנון יש שלושה לבבות ודם כחול.',
      'כפית מכוכב נויטרונים שוקלת 6 מיליארד טון.',
      'בננות הן רדיואקטיביות באופן טבעי.',
      'אתה חולק 60% מה-DNA שלך עם בננה.',
    ],
    History: [
      'קליאופטרה חיה קרוב יותר לנחיתה על הירח מאשר לבניית הפירמידות.',
      'אוניברסיטת אוקספורד עתיקה יותר מהאימפריה האצטקית.',
      'הוויקינגים השתמשו בגבישים כדי לנווט בימים מעוננים.',
      'הרומאים העתיקים השתמשו בשתן כמי פה.',
      'המלחמה הקצרה בהיסטוריה נמשכה 38 דקות.',
    ],
    Gaming: [
      'השם המקורי של מריו היה "ג\'אמפמן."',
      'פאקמן קיבל השראה מפיצה שחסר ממנה משולש.',
      'משחק הווידאו הראשון נוצר ב-1958 — Tennis for Two.',
      'למיינקראפט נמכרו יותר עותקים מכל משחק אחר.',
      'הפלייסטיישן היה במקור אביזר של נינטנדו.',
    ],
    Movies: [
      'שאגת האריה בלוגו של MGM היא בעצם של נמר.',
      'צעצוע של סיפור היה סרט העלילה הראשון שנעשה כולו בהנפשת מחשב.',
      'המילה "מאפיה" לא נאמרת אף פעם בסנדק.',
      'ג\'יימס בונד גולם על ידי 7 שחקנים שונים.',
      'הסרט טיטניק עלה יותר מהספינה עצמה.',
    ],
    Music: [
      '"יום הולדת שמח" היה מוגן בזכויות יוצרים עד 2016.',
      'השיר המושמע ביותר בספוטיפיי עבר 4 מיליארד השמעות.',
      'בטהובן המשיך להלחין אחרי שהתחרש לחלוטין.',
      'לקבוצת פלמינגו קוראים באנגלית "flamboyance" — רהבתנות.',
      'הקונצרט הארוך ביותר אי פעם נמשך מעל 453 שעות.',
    ],
    Sports: [
      'גולף הוא הספורט היחיד ששיחקו על הירח.',
      'מדליות זהב אולימפיות עשויות בעיקר מכסף.',
      'כדור בייסבול מחזיק בממוצע רק 5 עד 7 זריקות.',
      'טניס שוחק במקור בידיים חשופות.',
      'המשחקים האולימפיים הראשונים כללו תחרות אחת בלבד: מרוץ ריצה.',
    ],
    Nature: [
      'עצים מתקשרים דרך רשת פטריות תת-קרקעית.',
      'ברק חם פי 5 מפני השטח של השמש.',
      'לפרות יש חברות הכי טובות והן נלחצות כשמפרידות ביניהן.',
      'יש יותר עצים על כדור הארץ מכוכבים בשביל החלב.',
      'עצלנים יכולים לעצור את נשימתם לזמן ארוך יותר מדולפינים.',
    ],
    Food: [
      'תותים הם בעצם לא גרגרים — בננות דווקא כן.',
      'דבש הוא המזון היחיד שלא פג תוקפו לעולם.',
      'גזרים היו במקור סגולים, לא כתומים.',
      'תפוחים צפים כי הם 25% אוויר.',
      'בוטנים הם לא אגוזים — הם קטניות.',
    ],
    Travel: [
      'צרפת היא המדינה המתוירת ביותר בעולם.',
      'יש עיר בנורווגיה בשם "Hell" — והיא קופאת בחורף.',
      'אוסטרליה רחבה יותר מהירח.',
      'הטיסה הקצרה ביותר בעולם נמשכת 57 שניות.',
      'בקנדה יש יותר אגמים מאשר בכל שאר העולם ביחד.',
    ],
    'Pop Culture': [
      'הודעת הטקסט הראשונה שנשלחה אי פעם אמרה פשוט "Merry Christmas."',
      'יותר אנשים מחזיקים טלפונים מאשר מברשות שיניים.',
      'לסימן # קוראים באנגלית "אוקטותורפ."',
      'האדם הממוצע מבלה שבועיים מחייו בהמתנה ברמזורים.',
      'אמוג\'ים הומצאו ביפן ב-1999.',
    ],
    Art: [
      'למונה ליזה יש תיבת דואר משלה למכתבי מעריצים.',
      'וינסנט ואן גוך מכר רק ציור אחד בחייו.',
      'הצבע כתום נקרא על שם הפרי, לא להפך.',
      'פיקאסו ידע לצייר לפני שידע ללכת.',
      'ייקח 100 ימים לראות כל יצירה בלובר למשך 30 שניות.',
    ],
    Tech: [
      'הבאג הראשון במחשב היה עש אמיתי שנתקע במכונה.',
      'אימייל היה קיים לפני הרשת העולמית.',
      'הדיסק הקשיח הראשון בנפח 1GB שקל מעל 225 קילו.',
      'כ-90% מהנתונים בעולם נוצרו בשנתיים האחרונות.',
      'האתר הראשון מ-1991 עדיין פעיל באינטרנט.',
    ],
  },

  ru: {
    Science: [
      'Мёд не портится — банки возрастом 3 000 лет всё ещё пригодны для еды.',
      'У осьминогов три сердца и голубая кровь.',
      'Чайная ложка нейтронной звезды весит 6 миллиардов тонн.',
      'Бананы от природы радиоактивны.',
      'У вас 60% общих генов с бананом.',
    ],
    History: [
      'Клеопатра жила ближе по времени к высадке на Луну, чем к строительству пирамид.',
      'Оксфордский университет старше империи ацтеков.',
      'Викинги использовали кристаллы для навигации в пасмурную погоду.',
      'Древние римляне использовали мочу как ополаскиватель для рта.',
      'Самая короткая война в истории длилась 38 минут.',
    ],
    Gaming: [
      'Марио изначально звали «Джампмен».',
      'Пакман был вдохновлён пиццей с недостающим куском.',
      'Первая видеоигра была создана в 1958 году — Tennis for Two.',
      'Minecraft — самая продаваемая видеоигра в истории.',
      'PlayStation изначально создавался как аксессуар для Nintendo.',
    ],
    Movies: [
      'Рычание льва в заставке MGM на самом деле принадлежит тигру.',
      '«История игрушек» — первый полнометражный фильм, полностью созданный на компьютере.',
      'Слово «мафия» ни разу не произносится в «Крёстном отце».',
      'Джеймса Бонда играли 7 разных актёров.',
      'Фильм «Титаник» обошёлся дороже, чем сам корабль.',
    ],
    Music: [
      'Песня «Happy Birthday» была защищена авторским правом до 2016 года.',
      'Самый прослушиваемый трек на Spotify набрал более 4 миллиардов воспроизведений.',
      'Бетховен продолжал сочинять музыку, полностью оглохнув.',
      'Группу фламинго по-английски называют «flamboyance» — великолепие.',
      'Самый длинный концерт в истории длился более 453 часов.',
    ],
    Sports: [
      'Гольф — единственный вид спорта, в который играли на Луне.',
      'Олимпийские золотые медали в основном сделаны из серебра.',
      'Бейсбольный мяч выдерживает в среднем всего 5–7 подач.',
      'В теннис изначально играли голыми руками.',
      'На первых Олимпийских играх был только один вид спорта: бег.',
    ],
    Nature: [
      'Деревья общаются через подземную грибную сеть.',
      'Молния в 5 раз горячее поверхности Солнца.',
      'У коров есть лучшие друзья, и они переживают, когда их разлучают.',
      'На Земле больше деревьев, чем звёзд в Млечном Пути.',
      'Ленивцы могут задерживать дыхание дольше, чем дельфины.',
    ],
    Food: [
      'Клубника на самом деле не ягода, а вот банан — ягода.',
      'Мёд — единственный продукт, который никогда не портится.',
      'Морковь изначально была фиолетовой, а не оранжевой.',
      'Яблоки плавают, потому что на 25% состоят из воздуха.',
      'Арахис — это не орех, а бобовое растение.',
    ],
    Travel: [
      'Франция — самая посещаемая страна в мире.',
      'В Норвегии есть город под названием «Хелл» — и там бывают заморозки.',
      'Австралия шире Луны.',
      'Самый короткий авиарейс в мире длится 57 секунд.',
      'В Канаде больше озёр, чем во всём остальном мире вместе взятом.',
    ],
    'Pop Culture': [
      'Первое SMS-сообщение содержало всего два слова: «Merry Christmas».',
      'Телефонов в мире больше, чем зубных щёток.',
      'Символ # на самом деле называется «октоторп».',
      'В среднем человек проводит 2 недели жизни в ожидании у светофоров.',
      'Эмодзи были изобретены в Японии в 1999 году.',
    ],
    Art: [
      'У Моны Лизы есть собственный почтовый ящик для писем от поклонников.',
      'Винсент Ван Гог продал лишь одну картину за всю жизнь.',
      'Цвет «оранжевый» назван в честь фрукта, а не наоборот.',
      'Пикассо умел рисовать раньше, чем ходить.',
      'Чтобы увидеть каждый экспонат в Лувре хотя бы на 30 секунд, понадобится 100 дней.',
    ],
    Tech: [
      'Первый компьютерный «баг» был настоящей молью, застрявшей в машине.',
      'Электронная почта появилась раньше Всемирной паутины.',
      'Первый жёсткий диск объёмом 1 ГБ весил более 225 кг.',
      'Около 90% всех данных в мире были созданы за последние 2 года.',
      'Первый в мире веб-сайт 1991 года до сих пор работает.',
    ],
  },

  de: {
    Science: [
      'Honig verdirbt nie — 3.000 Jahre alte Gläser schmecken noch einwandfrei.',
      'Kraken haben drei Herzen und blaues Blut.',
      'Ein Teelöffel eines Neutronensterns wiegt 6 Milliarden Tonnen.',
      'Bananen sind von Natur aus radioaktiv.',
      'Du teilst 60 % deiner DNA mit einer Banane.',
    ],
    History: [
      'Kleopatra lebte zeitlich näher an der Mondlandung als am Bau der Pyramiden.',
      'Die Universität Oxford ist älter als das Azteken-Reich.',
      'Wikinger nutzten Kristalle, um bei bewölktem Himmel zu navigieren.',
      'Die alten Römer benutzten Urin als Mundspülung.',
      'Der kürzeste Krieg der Geschichte dauerte 38 Minuten.',
    ],
    Gaming: [
      'Mario hieß ursprünglich „Jumpman".',
      'Pac-Man wurde von einer Pizza mit einem fehlenden Stück inspiriert.',
      'Das erste Videospiel entstand 1958 — Tennis for Two.',
      'Minecraft hat mehr verkaufte Exemplare als jedes andere Spiel.',
      'Die PlayStation war ursprünglich ein Zubehör für Nintendo.',
    ],
    Movies: [
      'Das Löwengebrüll im MGM-Logo stammt in Wirklichkeit von einem Tiger.',
      'Toy Story war der erste komplett computeranimierte Spielfilm.',
      'Das Wort „Mafia" fällt im Film Der Pate kein einziges Mal.',
      'James Bond wurde von 7 verschiedenen Schauspielern dargestellt.',
      'Der Film Titanic kostete mehr als das echte Schiff.',
    ],
    Music: [
      '„Happy Birthday" war bis 2016 urheberrechtlich geschützt.',
      'Der meistgestreamte Song auf Spotify hat über 4 Milliarden Aufrufe.',
      'Beethoven komponierte weiter, nachdem er vollständig ertaubt war.',
      'Eine Gruppe Flamingos heißt auf Englisch „Flamboyance" — Extravaganz.',
      'Das längste Konzert aller Zeiten dauerte über 453 Stunden.',
    ],
    Sports: [
      'Golf ist die einzige Sportart, die auf dem Mond gespielt wurde.',
      'Olympische Goldmedaillen bestehen größtenteils aus Silber.',
      'Ein Baseball hält im Schnitt nur 5–7 Würfe.',
      'Tennis wurde ursprünglich mit bloßen Händen gespielt.',
      'Bei den ersten Olympischen Spielen gab es nur eine Disziplin: einen Wettlauf.',
    ],
    Nature: [
      'Bäume kommunizieren über ein unterirdisches Pilznetzwerk.',
      'Ein Blitz ist 5-mal heißer als die Sonnenoberfläche.',
      'Kühe haben beste Freunde und werden gestresst, wenn man sie trennt.',
      'Es gibt mehr Bäume auf der Erde als Sterne in der Milchstraße.',
      'Faultiere können länger die Luft anhalten als Delfine.',
    ],
    Food: [
      'Erdbeeren sind eigentlich keine Beeren — Bananen dagegen schon.',
      'Honig ist das einzige Lebensmittel, das niemals verdirbt.',
      'Karotten waren ursprünglich lila, nicht orange.',
      'Äpfel schwimmen, weil sie zu 25 % aus Luft bestehen.',
      'Erdnüsse sind keine Nüsse — sie sind Hülsenfrüchte.',
    ],
    Travel: [
      'Frankreich ist das meistbesuchte Land der Welt.',
      'In Norwegen gibt es einen Ort namens „Hell" — und er friert regelmäßig ein.',
      'Australien ist breiter als der Mond.',
      'Der kürzeste Flug der Welt dauert 57 Sekunden.',
      'Kanada hat mehr Seen als der Rest der Welt zusammen.',
    ],
    'Pop Culture': [
      'Die erste SMS aller Zeiten lautete einfach „Merry Christmas".',
      'Mehr Menschen besitzen ein Handy als eine Zahnbürste.',
      'Das #-Zeichen heißt eigentlich „Octothorpe".',
      'Der Durchschnittsmensch verbringt 2 Wochen seines Lebens an roten Ampeln.',
      'Emojis wurden 1999 in Japan erfunden.',
    ],
    Art: [
      'Die Mona Lisa hat ihren eigenen Briefkasten für Fanbriefe.',
      'Vincent van Gogh verkaufte zu Lebzeiten nur ein einziges Gemälde.',
      'Die Farbe Orange ist nach der Frucht benannt, nicht umgekehrt.',
      'Picasso konnte zeichnen, bevor er laufen konnte.',
      'Man bräuchte 100 Tage, um jedes Werk im Louvre 30 Sekunden lang zu betrachten.',
    ],
    Tech: [
      'Der erste Computer-Bug war eine echte Motte in der Maschine.',
      'E-Mail gab es schon vor dem World Wide Web.',
      'Die erste 1-GB-Festplatte wog über 225 Kilogramm.',
      'Rund 90 % aller Daten weltweit wurden in den letzten 2 Jahren erzeugt.',
      'Die erste Webseite von 1991 ist immer noch online.',
    ],
  },

  pl: {
    Science: [
      'Miód nigdy się nie psuje — 3000-letnie słoiki wciąż nadają się do jedzenia.',
      'Ośmiornice mają trzy serca i niebieską krew.',
      'Łyżeczka gwiazdy neutronowej waży 6 miliardów ton.',
      'Banany są naturalnie radioaktywne.',
      'Dzielisz 60% swojego DNA z bananem.',
    ],
    History: [
      'Kleopatra żyła bliżej czasów lądowania na Księżycu niż budowy piramid.',
      'Uniwersytet Oksfordzki jest starszy od imperium Azteków.',
      'Wikingowie używali kryształów do nawigacji w pochmurne dni.',
      'Starożytni Rzymianie używali moczu jako płynu do płukania ust.',
      'Najkrótsza wojna w historii trwała 38 minut.',
    ],
    Gaming: [
      'Mario początkowo nazywał się „Jumpman".',
      'Pac-Man został zainspirowany pizzą z brakującym kawałkiem.',
      'Pierwsza gra wideo powstała w 1958 roku — Tennis for Two.',
      'Minecraft ma więcej sprzedanych kopii niż jakakolwiek inna gra.',
      'PlayStation był pierwotnie akcesorium do Nintendo.',
    ],
    Movies: [
      'Ryk lwa w logo MGM to w rzeczywistości ryk tygrysa.',
      'Toy Story był pierwszym pełnometrażowym filmem stworzonym w całości komputerowo.',
      'Słowo „mafia" nie pada ani razu w filmie Ojciec Chrzestny.',
      'James Bond był grany przez 7 różnych aktorów.',
      'Film Titanic kosztował więcej niż sam statek.',
    ],
    Music: [
      '„Happy Birthday" było objęte prawem autorskim aż do 2016 roku.',
      'Najczęściej odtwarzany utwór na Spotify ma ponad 4 miliardy odsłuchań.',
      'Beethoven nadal komponował po całkowitej utracie słuchu.',
      'Grupa flamingów po angielsku nazywa się „flamboyance" — ostentacja.',
      'Najdłuższy koncert w historii trwał ponad 453 godziny.',
    ],
    Sports: [
      'Golf to jedyny sport, w który grano na Księżycu.',
      'Olimpijskie złote medale są w większości zrobione ze srebra.',
      'Piłka bejsbolowa wytrzymuje średnio tylko 5–7 rzutów.',
      'W tenisa pierwotnie grano gołymi rękami.',
      'Pierwsze igrzyska olimpijskie miały tylko jedną konkurencję: bieg.',
    ],
    Nature: [
      'Drzewa komunikują się przez podziemną sieć grzybni.',
      'Błyskawica jest 5 razy gorętsza niż powierzchnia Słońca.',
      'Krowy mają najlepsze przyjaciółki i stresują się, gdy je rozdzielisz.',
      'Na Ziemi jest więcej drzew niż gwiazd w Drodze Mlecznej.',
      'Leniwce potrafią wstrzymać oddech dłużej niż delfiny.',
    ],
    Food: [
      'Truskawki to właściwie nie jagody — za to banany jak najbardziej.',
      'Miód to jedyne jedzenie, które nigdy się nie przeterminuje.',
      'Marchewki były pierwotnie fioletowe, a nie pomarańczowe.',
      'Jabłka unoszą się na wodzie, bo składają się w 25% z powietrza.',
      'Orzeszki ziemne to nie orzechy — to rośliny strączkowe.',
    ],
    Travel: [
      'Francja jest najczęściej odwiedzanym krajem na świecie.',
      'W Norwegii jest miasteczko o nazwie „Hell" — i regularnie tam zamarza.',
      'Australia jest szersza niż Księżyc.',
      'Najkrótszy lot na świecie trwa 57 sekund.',
      'Kanada ma więcej jezior niż cała reszta świata razem wzięta.',
    ],
    'Pop Culture': [
      'Pierwsza wiadomość SMS brzmiała po prostu „Merry Christmas".',
      'Więcej ludzi ma telefony niż szczoteczki do zębów.',
      'Symbol # oficjalnie nazywa się „octothorpe".',
      'Przeciętny człowiek spędza 2 tygodnie życia czekając na zielone światło.',
      'Emoji zostały wynalezione w Japonii w 1999 roku.',
    ],
    Art: [
      'Mona Lisa ma własną skrzynkę pocztową na listy od fanów.',
      'Vincent van Gogh sprzedał za życia tylko jeden obraz.',
      'Kolor pomarańczowy został nazwany od owocu, a nie odwrotnie.',
      'Picasso potrafił rysować, zanim nauczył się chodzić.',
      'Obejrzenie każdego dzieła w Luwrze przez 30 sekund zajęłoby 100 dni.',
    ],
    Tech: [
      'Pierwszy komputerowy „bug" był prawdziwą ćmą, która utknęła w maszynie.',
      'E-mail istniał przed powstaniem World Wide Web.',
      'Pierwszy dysk twardy o pojemności 1 GB ważył ponad 225 kilogramów.',
      'Około 90% światowych danych powstało w ciągu ostatnich 2 lat.',
      'Pierwsza strona internetowa z 1991 roku wciąż działa.',
    ],
  },

  es: {
    Science: [
      'La miel nunca se echa a perder — frascos de 3.000 años siguen en buen estado.',
      'Los pulpos tienen tres corazones y sangre azul.',
      'Una cucharadita de una estrella de neutrones pesa 6 mil millones de toneladas.',
      'Los plátanos son naturalmente radiactivos.',
      'Compartes el 60% de tu ADN con un plátano.',
    ],
    History: [
      'Cleopatra vivió más cerca del alunizaje que de la construcción de las pirámides.',
      'La Universidad de Oxford es más antigua que el Imperio Azteca.',
      'Los vikingos usaban cristales para navegar en días nublados.',
      'Los antiguos romanos usaban orina como enjuague bucal.',
      'La guerra más corta de la historia duró 38 minutos.',
    ],
    Gaming: [
      'Mario se llamaba originalmente "Jumpman."',
      'Pac-Man se inspiró en una pizza a la que le faltaba un trozo.',
      'El primer videojuego se creó en 1958 — Tennis for Two.',
      'Minecraft ha vendido más copias que cualquier otro juego.',
      'La PlayStation fue originalmente un accesorio de Nintendo.',
    ],
    Movies: [
      'El rugido de león del logo de MGM es en realidad de un tigre.',
      'Toy Story fue el primer largometraje hecho completamente por computadora.',
      'La palabra "mafia" nunca se dice en El Padrino.',
      'James Bond ha sido interpretado por 7 actores diferentes.',
      'La película Titanic costó más que el barco real.',
    ],
    Music: [
      '"Cumpleaños Feliz" estuvo protegido por derechos de autor hasta 2016.',
      'La canción más reproducida en Spotify tiene más de 4 mil millones de reproducciones.',
      'Beethoven siguió componiendo después de quedarse completamente sordo.',
      'A un grupo de flamencos en inglés se le llama "flamboyance" — extravagancia.',
      'El concierto más largo de la historia duró más de 453 horas.',
    ],
    Sports: [
      'El golf es el único deporte que se ha jugado en la Luna.',
      'Las medallas de oro olímpicas están hechas principalmente de plata.',
      'Una pelota de béisbol dura en promedio solo 5 a 7 lanzamientos.',
      'El tenis se jugaba originalmente con las manos desnudas.',
      'Los primeros Juegos Olímpicos solo tenían una prueba: una carrera a pie.',
    ],
    Nature: [
      'Los árboles se comunican a través de una red subterránea de hongos.',
      'Un rayo es 5 veces más caliente que la superficie del Sol.',
      'Las vacas tienen mejores amigas y se estresan cuando las separan.',
      'Hay más árboles en la Tierra que estrellas en la Vía Láctea.',
      'Los perezosos pueden aguantar la respiración más tiempo que los delfines.',
    ],
    Food: [
      'Las fresas en realidad no son bayas — los plátanos sí lo son.',
      'La miel es el único alimento que nunca caduca.',
      'Las zanahorias eran originalmente moradas, no naranjas.',
      'Las manzanas flotan porque son 25% aire.',
      'Los cacahuetes no son frutos secos — son legumbres.',
    ],
    Travel: [
      'Francia es el país más visitado del mundo.',
      'Hay un pueblo en Noruega llamado "Hell" — y se congela en invierno.',
      'Australia es más ancha que la Luna.',
      'El vuelo más corto del mundo dura 57 segundos.',
      'Canadá tiene más lagos que el resto del mundo junto.',
    ],
    'Pop Culture': [
      'El primer mensaje de texto enviado decía simplemente "Merry Christmas."',
      'Más personas tienen teléfonos que cepillos de dientes.',
      'El símbolo # técnicamente se llama "octothorpe."',
      'La persona promedio pasa 2 semanas de su vida esperando en semáforos.',
      'Los emojis se inventaron en Japón en 1999.',
    ],
    Art: [
      'La Mona Lisa tiene su propio buzón para cartas de admiradores.',
      'Vincent van Gogh solo vendió un cuadro en toda su vida.',
      'El color naranja lleva el nombre de la fruta, no al revés.',
      'Picasso sabía dibujar antes de aprender a caminar.',
      'Se necesitarían 100 días para ver cada obra del Louvre durante 30 segundos.',
    ],
    Tech: [
      'El primer "bug" informático fue una polilla real atrapada en la máquina.',
      'El correo electrónico existió antes de la World Wide Web.',
      'El primer disco duro de 1 GB pesaba más de 225 kilogramos.',
      'Aproximadamente el 90% de los datos del mundo se crearon en los últimos 2 años.',
      'El primer sitio web de 1991 sigue en línea.',
    ],
  },
};

// General facts as fallback
const generalFacts: Record<Language, string[]> = {
  en: [
    'A day on Venus is longer than its year.',
    'Sharks are older than trees.',
    'The inventor of the Pringles can is buried in one.',
    'Scotland\'s national animal is the unicorn.',
    'A jiffy is an actual unit of time: 1/100th of a second.',
    'The human nose can detect over 1 trillion scents.',
    'Wombat poop is cube-shaped.',
    'There are more possible chess games than atoms in the universe.',
  ],
  he: [
    'יום על נוגה ארוך יותר משנה שלמה שם.',
    'כרישים קדומים יותר מעצים.',
    'הממציא של קופסת פרינגלס נקבר בתוך אחת.',
    'חיית המדינה של סקוטלנד היא חד-קרן.',
    'ג\'יפי הוא יחידת זמן אמיתית: מאית השנייה.',
    'האף האנושי יכול לזהות מעל טריליון ריחות.',
    'הגללים של וומבט הם בצורת קוביה.',
    'יש יותר משחקי שחמט אפשריים מאשר אטומים ביקום.',
  ],
  ru: [
    'День на Венере длиннее, чем её год.',
    'Акулы древнее деревьев.',
    'Изобретатель банки Pringles похоронен в одной из них.',
    'Национальное животное Шотландии — единорог.',
    'Джиффи — настоящая единица времени: одна сотая секунды.',
    'Человеческий нос способен различать более триллиона запахов.',
    'Фекалии вомбата имеют форму куба.',
    'Возможных шахматных партий больше, чем атомов во Вселенной.',
  ],
  de: [
    'Ein Tag auf der Venus ist länger als ein ganzes Venus-Jahr.',
    'Haie sind älter als Bäume.',
    'Der Erfinder der Pringles-Dose wurde in einer beerdigt.',
    'Schottlands Nationaltier ist das Einhorn.',
    'Ein Jiffy ist eine echte Zeiteinheit: eine Hundertstelsekunde.',
    'Die menschliche Nase kann über eine Billion Gerüche unterscheiden.',
    'Wombat-Kot ist würfelförmig.',
    'Es gibt mehr mögliche Schachpartien als Atome im Universum.',
  ],
  pl: [
    'Dzień na Wenus jest dłuższy niż jej rok.',
    'Rekiny są starsze niż drzewa.',
    'Wynalazca puszki Pringles został w niej pochowany.',
    'Narodowym zwierzęciem Szkocji jest jednorożec.',
    'Jiffy to prawdziwa jednostka czasu: jedna setna sekundy.',
    'Ludzki nos potrafi rozróżnić ponad bilion zapachów.',
    'Odchody wombata mają kształt sześcianu.',
    'Możliwych partii szachowych jest więcej niż atomów we wszechświecie.',
  ],
  es: [
    'Un día en Venus dura más que su propio año.',
    'Los tiburones son más antiguos que los árboles.',
    'El inventor del bote de Pringles fue enterrado en uno.',
    'El animal nacional de Escocia es el unicornio.',
    'Un jiffy es una unidad de tiempo real: una centésima de segundo.',
    'La nariz humana puede detectar más de un billón de olores.',
    'Las heces de los wombats tienen forma de cubo.',
    'Hay más partidas de ajedrez posibles que átomos en el universo.',
  ],
};

let lastFactIndex = -1;

export function getRandomFunFact(subject?: string | null, language: Language = 'en'): string {
  const langFacts = funFacts[language] || funFacts.en;
  const langGeneral = generalFacts[language] || generalFacts.en;

  const pool = subject && langFacts[subject]
    ? [...langFacts[subject], ...langGeneral]
    : langGeneral;

  // Avoid repeating the same fact back to back
  let index: number;
  do {
    index = Math.floor(Math.random() * pool.length);
  } while (index === lastFactIndex && pool.length > 1);

  lastFactIndex = index;
  return pool[index];
}
